// config/enemies.js
const DISPLAY_SCALE = 1;
const HITBOX_SCALE = 1;
const scaleDimension = ({ width, height }) => ({
    width: Math.max(2, Math.round((width ?? 0) * DISPLAY_SCALE)),
    height: Math.max(2, Math.round((height ?? 0) * DISPLAY_SCALE))
});
const scaleHitbox = ({ width, height }) => ({
    width: Math.max(2, Math.round((width ?? 0) * HITBOX_SCALE)),
    height: Math.max(2, Math.round((height ?? 0) * HITBOX_SCALE))
});

export const ENEMIES = {
    skeleton: {
        name: 'Skeleton',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 550,
        behavior: 'chase',
        texture: 'skeleton',
        scale: 1,
        displaySize: scaleDimension({ width: 20, height: 20 }),
        hitboxSize: scaleHitbox({ width: 25, height: 25 }),
        attackRange: 40,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        knockbackResist: 0.8
    },
    succubus: {
        name: 'Succubus',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 550,
        behavior: 'chase',
        texture: 'succubus',
        scale: 1,
        displaySize: scaleDimension({ width: 20, height: 20 }),
        hitboxSize: scaleHitbox({ width: 25, height: 25 }),
        attackRange: 40,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        knockbackResist: 0.8
    },
    lamia: {
        name: 'Lamia',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 550,
        behavior: 'chase',
        texture: 'lamia',
        scale: 1,
        displaySize: scaleDimension({ width: 20, height: 20 }),
        hitboxSize: scaleHitbox({ width: 25, height: 25 }),
        attackRange: 40,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        knockbackResist: 0.8
    },
    moth_woman: {
        name: 'Moth Woman',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'moth_woman',
        scale: 1,
        displaySize: scaleDimension({ width: 20, height: 20 }),
        hitboxSize: scaleHitbox({ width: 20, height: 20 }),
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
        knockbackResist: 1,
        attackEffectTint: 0x000000,
        attackGlowColors: [0x000000, 0x111111],
        attackSparkTints: [0x000000]
    },
    widow: {
        name: 'Widow',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'widow',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
    },
    medusa: {
        name: 'Medusa',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'medusa',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        isBoss: true
    }
    ,
    minotau: {
        name: 'Minotau',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'minotau',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        isBoss: true
    }
    ,
    baphomet: {
        name: 'Baphomet',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'baphomet',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        isBoss: true
    }
    ,
    dino: {
        name: 'Dino',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'dino',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        isBoss: true
    }
    ,
    bugmonster: {
        name: 'Bug Monster',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'bugmonster',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        isBoss: true
    }
    ,
    cursed_maiden: {
        name: 'Cursed Maiden',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'cursed_maiden',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        isBoss: true
    }
    ,
    kitsume: {
        name: 'Kitsume',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'kitsume',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
    }
    ,
    mummy: {
        name: 'Mummy',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'mummy',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
    }
    ,
    zombie_woman: {
        name: 'Zombie Woman',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'zombie_woman',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
        knockbackResist: 9
    }
    ,
    slime: {
        name: 'Slime',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'slime',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
    },
    worm: {
        name: 'Worm',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'worm',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
    },
    rat: {
        name: 'Rat',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'rat',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
    },
    bat: {
        name: 'Bat',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'bat',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
    },
    demonbat: {
        name: 'Demon Bat',
        health: 10,
        speed: 35,
        damage: 10,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'demonbat',
        scale: 1,
        displaySize: { width: 20, height: 20 },
        hitboxSize: { width: 25, height: 25 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 6,
    }
    // Add more enemy types
};
