// config/enemies.js
const DISPLAY_SCALE = 2;
const HITBOX_SCALE = 2;
const scaleDimension = ({ width, height }) => ({
    width: Math.max(2, Math.round((width ?? 0) * DISPLAY_SCALE)),
    height: Math.max(2, Math.round((height ?? 0) * DISPLAY_SCALE))
});
const scaleHitbox = ({ width, height }) => ({
    width: Math.max(2, Math.round((width ?? 0) * HITBOX_SCALE)),
    height: Math.max(2, Math.round((height ?? 0) * HITBOX_SCALE))
});

export const ENEMIES = {
    zombie: {
        name: 'Zombie',
        health: 50,
        speed: 50,
        damage: 10,
        attackCooldown: 600,
        behavior: 'chase', // 'chase', 'wander', 'idle'
        texture: 'enemy',
        scale: 1,
        displaySize: scaleDimension({ width: 32, height: 32 }),
        hitboxSize: scaleHitbox({ width: 50, height: 50 }),
        attackRange: 30,
        xp: 15,
        spawnWeight: 5,
        unlockLevel: 999,
        knockbackResist: 1,
        attackEffectTint: 0x000000,
        attackGlowColors: [0x000000, 0x111111],
        attackSparkTints: [0x000000]
    },
    succubus: {
        name: 'Succubus',
        health: 900,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'succubus',
        scale: 1,
        displaySize: scaleDimension({ width: 25, height: 25 }),
        hitboxSize: scaleHitbox({ width: 30, height: 30 }),
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1,
        knockbackResist: 1,
        attackEffectTint: 0x000000,
        attackGlowColors: [0x000000, 0x111111],
        attackSparkTints: [0x000000]
    },
    harpy: {
        name: 'Harpy',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'harpy',
        scale: 1,
        displaySize: scaleDimension({ width: 25, height: 25 }),
        hitboxSize: scaleHitbox({ width: 30, height: 30 }),
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1,
        knockbackResist: 1,
        attackEffectTint: 0x000000,
        attackGlowColors: [0x000000, 0x111111],
        attackSparkTints: [0x000000]
    },
    skeleton: {
        name: 'Skeleton',
        health: 80,
        speed: 70,
        damage: 18,
        attackCooldown: 550,
        behavior: 'chase',
        texture: 'skeleton',
        scale: 1,
        displaySize: scaleDimension({ width: 25, height: 25 }),
        hitboxSize: scaleHitbox({ width: 30, height: 30 }),
        attackRange: 40,
        xp: 15 ,
        flashTint: 0xff0000,
        flashDuration: 120,
        spawnWeight: 3,
        unlockLevel: 1,
        knockbackResist: 0.8
    }
    ,
    moth_woman: {
        name: 'Moth Woman',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'moth_woman',
        scale: 1,
        displaySize: scaleDimension({ width: 25, height: 25 }),
        hitboxSize: scaleHitbox({ width: 30, height: 30 }),
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1,
        knockbackResist: 1,
        attackEffectTint: 0x000000,
        attackGlowColors: [0x000000, 0x111111],
        attackSparkTints: [0x000000]
    }
    ,
    siren: {
        name: 'Siren',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'siren',
        scale: 1,
        displaySize: scaleDimension({ width: 25, height: 25 }),
        hitboxSize: scaleHitbox({ width: 30, height: 30 }),
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1
    }
    ,
    widow: {
        name: 'Widow',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'widow',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1
    }
    ,
    medusa: {
        name: 'Medusa',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'medusa',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 3,
        unlockLevel: 1,
        isBoss: true
    }
    ,
    minotau: {
        name: 'Minotau',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'minotau',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 3,
        unlockLevel: 1,
        isBoss: true
    }
    ,
    baphomet: {
        name: 'Baphomet',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'baphomet',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 3,
        unlockLevel: 1,
        isBoss: true
    }
    ,
    dino: {
        name: 'Dino',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'dino',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 3,
        unlockLevel: 1,
        isBoss: true
    }
    ,
    bugmonster: {
        name: 'Bug Monster',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'bugmonster',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 3,
        unlockLevel: 1,
        isBoss: true
    }
    ,
    cursed_maiden: {
        name: 'Cursed Maiden',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'cursed_maiden',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 3,
        unlockLevel: 1,
        isBoss: true
    }
    ,
    kitsume: {
        name: 'Kitsume',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'kitsume',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1
    }
    ,
    mummy: {
        name: 'Mummy',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'mummy',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1
    }
    ,
    zombie_woman: {
        name: 'Zombie Woman',
        health: 990,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'zombie_woman',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1,
        knockbackResist: 9
    }
    ,
    slime: {
        name: 'Slime',
        health: 10,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'slime',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 200,
        spawnWeight: 6,
        unlockLevel: 1
    },
    worm: {
        name: 'Worm',
        health: 90,
        speed: 40,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'worm',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1
    },
    rat: {
        name: 'Rat',
        health: 90,
        speed: 130,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'rat',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1
    },
    bat: {
        name: 'Bat',
        health: 90,
        speed: 70,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'bat',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1
    },
    demonbat: {
        name: 'Demon Bat',
        health: 90,
        speed: 70,
        damage: 15,
        attackCooldown: 450,
        behavior: 'chase',
        texture: 'demonbat',
        scale: 1,
        displaySize: { width: 25, height: 25 },
        hitboxSize: { width: 30, height: 30 },
        attackRange: 20,
        flashTint: 0xff0000,
        flashDuration: 120,
        xp: 12,
        spawnWeight: 6,
        unlockLevel: 1
    }
    // Add more enemy types
};
